#!/bin/sh

OSX_VERS=$(sw_vers -productVersion | awk -F "." '{print $2}')

# Override the default behavior of sshd on the target volume to be not disabled
if [ "$OSX_VERS" -ge 10 ]; then
    OVERRIDES_PLIST="$3/private/var/db/com.apple.xpc.launchd/disabled.plist"
    /usr/libexec/PlistBuddy -c 'Delete :com.openssh.sshd' "$OVERRIDES_PLIST"
    /usr/libexec/PlistBuddy -c 'Add :com.openssh.sshd bool False' "$OVERRIDES_PLIST"
else
    OVERRIDES_PLIST="$3/private/var/db/launchd.db/com.apple.launchd/overrides.plist"
    /usr/libexec/PlistBuddy -c 'Delete :com.openssh.sshd' "$OVERRIDES_PLIST"
    /usr/libexec/PlistBuddy -c 'Add :com.openssh.sshd:Disabled bool False' "$OVERRIDES_PLIST"
fi

# Add vagrant to sudoers
cp "$3/etc/sudoers" "$3/etc/sudoers.orig"
echo 'vagrant ALL=(ALL) NOPASSWD: ALL' >> "$3/etc/sudoers"

# Add vagrant to admin group memberships (even though GID 80 is enough for most things)
VAGRANT_GUID=$(/usr/libexec/PlistBuddy -c 'Print :generateduid:0' "$3/private/var/db/dslocal/nodes/Default/users/vagrant.plist")
VAGRANT_UID=$(/usr/libexec/PlistBuddy -c 'Print :uid:0' "$3/private/var/db/dslocal/nodes/Default/users/vagrant.plist")
/usr/libexec/PlistBuddy -c 'Add :groupmembers: string $VAGRANT_GUID' "$3/private/var/db/dslocal/nodes/Default/groups/admin.plist"

# Pre-create vagrant user folder so veewee will have somewhere to scp configinfo to
mkdir -p "$3/Users/vagrant/Library/Preferences"

# Suppress annoying iCloud welcome on a GUI login
/usr/libexec/PlistBuddy -c 'Add :DidSeeCloudSetup bool true' "$3/Users/vagrant/Library/Preferences/com.apple.SetupAssistant.plist"
/usr/libexec/PlistBuddy -c 'Add :LastSeenCloudProductVersion string 10.9' "$3/Users/vagrant/Library/Preferences/com.apple.SetupAssistant.plist"

# Disable loginwindow screensaver to save CPU cycles
/usr/libexec/PlistBuddy -c 'Add :loginWindowIdleTime integer 0' "$3/Library/Preferences/com.apple.screensaver.plist"

# Fix ownership now that the above has made a Library folder as root
chown -R $VAGRANT_UID:20 "$3/Users/vagrant"

# Disable the welcome screen
touch "$3/private/var/db/.AppleSetupDone"
